# Generated by Django 4.1.4 on 2022-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='avatar',
            field=models.ImageField(default='', upload_to='host/avatar/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='properties/thubnail/'),
        ),
    ]
