# Generated by Django 4.1.4 on 2022-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_host_avatar_properties_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='places/thumbnail/')),
            ],
        ),
    ]
