# Generated by Django 4.1.4 on 2022-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
