# Generated by Django 4.1.4 on 2022-12-21 14:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_places_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
